var _$ = [
	'phone',
	'DOMContentLoaded',
	'onreadystatechange',
	'DOMContentLoaded',
	'onreadystatechange',
	'left',
	'string',
	'[object Object]',
	'number',
	'=',
	'; expires=',
	'',
	'; path=',
	'',
	'; domain=',
	'',
	'; secure',
	'',
	'',
	'(?:^|; )',
	'=([^;]*)',
	'on',
	'(^|&)',
	'=([^&]*)(&|$)',
	'i',
	'script',
	'http://m.xiaomi.com',
	'orgin',
	'mapp',
	'orgin',
	'/',
	'.xiaomi.com',
	'Android',
	'iPhone',
	'iPod',
	'Symbian',
	'xm_difft_hd',
	'/',
	'.xiaomi.com',
	'',
	'http://t.hd.xiaomi.com/s/',
	'xm_xt_prex',
	'/',
	'.xiaomi.com',
	'tv',
	'phone',
	'box',
	'http://tc.hd.xiaomi.com/hdget?callback=hdcontrol&_=',
	'jsonp',
	'xm_xt_prex',
	'xm_xt_prex',
	'4',
	'5',
	'6',
	'7',
	'8',
	'9',
	'10',
	'xm_difft_hd',
	'xm_difft_hd',
	'10/22/2013 12:00:00',
	'10/22/2013 12:02:00',
	'xm_xt_prex',
	'xm_difft_hd',
	'xm_difft_hd',
	'<span><ins>',
	'</ins>小时<ins>',
	'</ins>分<ins>',
	'</ins></span>秒后开始',
	'<span><ins>',
	'</ins>分<ins>',
	'</ins></span>秒后开始',
	'<span><ins>',
	'</ins></span>秒后开始',
	'surTime',
	'surTime',
	'boxbg',
	'box',
	'px',
	'block',
	'block',
	'boxbg',
	'box',
	'none',
	'none',
	'reback',
	'重新进入(<span id=\'initCount\'>',
	'</span>)',
	'http://order.xiaomi.com/event/getoption',
	'http://t.hd.xiaomi.com/r/?_a=payment_check_tv',
	'http://t.hd.xiaomi.com/r/?_a=payment_check_box',
	'http://t.hd.xiaomi.com/r/?_a=20131018&_op=check',
	'http://t.hd.xiaomi.com/r/?_a=20131018_tv&_op=check',
	'http://t.hd.xiaomi.com/c/?_a=20131022_phone_df56ab516d&_op=check',
	'http://t.hd.xiaomi.com/c/?_a=20131022_mi_tv_ae3cc600f&_op=check',
	'http://t.hd.xiaomi.com/c/?_a=20131022_box_f9348273e1&_op=check',
	'http://p.www.xiaomi.com/zt/xm_account/limitfacade.html?third=http%253A%252F%252Forder.xiaomi.com%252Flogin%252Fcallback%253Ffollowup%253Dhttp%25253A%25252F%25252Fp.www.xiaomi.com%25252Fopen%25252Findex.html%2526sign%253DYWY4NjlhMmExNzkzNGE5YTBjYjAzNzVjZTc1MmE5OTYwYmVlODc4NA%252C%252C%26sid%3Deshop&sid=eshop&callback=http%253A%252F%252Forder.xiaomi.com%252Flogin%252Fcallback%253Ffollowup%253Dhttp%25253A%25252F%25252Fp.www.xiaomi.com%25252Fopen%25252Findex.html%2526sign%253DYWY4NjlhMmExNzkzNGE5YTBjYjAzNzVjZTc1MmE5OTYwYmVlODc4NA%252C%252C&sign=9ZAFXvlDKGxSJhEBqKdOtQp633c%253D',
	'hdBtns',
	'hdSubTitle',
	'hdLnks',
	'hdMsg',
	'mi3btn',
	'mitvbtn',
	'detail-mi3',
	'detail-mi2s',
	'detail-hm',
	'detail-hz',
	'detail-mitv',
	'userId',
	'hdBtns',
	'hdBtns',
	'hdSubTitle',
	'hdLnks',
	'hdMsg',
	'mi3btn',
	'mitvbtn',
	'detail-mi3',
	'detail-mi2s',
	'detail-hm',
	'detail-hz',
	'detail-mitv',
	'hdBtns',
	'hdSubTitle',
	'hdLnks',
	'hdMsg',
	'mi3btn',
	'mitvbtn',
	'detail-mi3',
	'detail-mi2s',
	'detail-hm',
	'detail-hz',
	'detail-mitv',
	'hdBtns',
	'hdSubTitle',
	'hdLnks',
	'hdMsg',
	'mi3btn',
	'mitvbtn',
	'detail-mi3',
	'detail-mi2s',
	'detail-hm',
	'detail-hz',
	'detail-mitv',
	'hdBtns',
	'hdSubTitle',
	'hdLnks',
	'hdMsg',
	'mi3btn',
	'mitvbtn',
	'detail-mi3',
	'detail-mi2s',
	'detail-hm',
	'detail-hz',
	'detail-mitv',
	'hdBtns',
	'hdSubTitle',
	'hdLnks',
	'hdMsg',
	'mi3btn',
	'mitvbtn',
	'detail-mi3',
	'detail-mi2s',
	'detail-hm',
	'detail-hz',
	'detail-mitv',
	'hdBtns',
	'hdSubTitle',
	'hdLnks',
	'hdMsg',
	'mi3btn',
	'mitvbtn',
	'detail-mi3',
	'detail-mi2s',
	'detail-hm',
	'detail-hz',
	'detail-mitv',
	'hdBtns',
	'hdSubTitle',
	'hdLnks',
	'hdMsg',
	'mi3btn',
	'mitvbtn',
	'detail-mi3',
	'detail-mi2s',
	'detail-hm',
	'detail-hz',
	'detail-mitv',
	'hdBtns',
	'hdSubTitle',
	'hdLnks',
	'hdMsg',
	'mi3btn',
	'mitvbtn',
	'detail-mi3',
	'detail-mi2s',
	'detail-hm',
	'detail-hz',
	'detail-mitv',
	'hdBtns',
	'hdSubTitle',
	'hdLnks',
	'hdMsg',
	'mi3btn',
	'mitvbtn',
	'detail-mi3',
	'detail-mi2s',
	'detail-hm',
	'detail-hz',
	'detail-mitv',
	'<span class="untime"><label id="surTime" class="unbtn"></label></span>',
	'<a class="btn" href="',
	'" title="提前登录" >提前登录</a>',
	'<a class="btn" onClick="showBox(\'phone\');">购买手机</a><a class="btn" onClick="showBox(\'tv\');">购买电视</a><a class="btn" onClick="showBox(\'box\');">购买盒子</a>',
	'<a class="btn" href="',
	'" target="_blank">支付手机</a><a class="btn" href="',
	'" target="_blank">支付电视</a><a class="btn" href="',
	'" target="_blank">支付盒子</a>',
	'<a class="btn" onClick="showBox(\'phone\');">购买手机</a><a class="btn" onClick="showBox(\'box\');">购买盒子</a><a class="btn" href="',
	'" target="_blank">支付电视</a>',
	'<a class="btn" onClick="showBox(\'tv\');">购买电视</a><a class="btn" onClick="showBox(\'box\');">购买盒子</a><a class="btn" href="',
	'" target="_blank">支付手机</a>',
	'<a class="btn" onClick="showBox(\'box\');">购买盒子</a><a class="btn" href="',
	'">支付手机</a><a class="btn" href="',
	'" target="_blank">支付电视</a>',
	'<a class="btn" onClick="showBox(\'phone\');">购买手机</a><a class="btn" href="',
	'" target="_blank">支付电视</a><a class="btn" href="',
	'" target="_blank">支付盒子</a>',
	'<a class="btn" onClick="showBox(\'tv\');">购买电视</a><a class="btn" href="',
	'" target="_blank">支付手机</a><a class="btn" href="',
	'" target="_blank">支付盒子</a>',
	'<a class="btn" onClick="showBox(\'phone\');">购买手机</a><a class="btn" onClick="showBox(\'tv\');">购买电视</a><a class="btn" href="',
	'" target="_blank">支付盒子</a>',
	'10月22日星期二 中午12点<br/>小米手机3、小米电视第二轮开放购买<br/>还有小米2S、红米手机、小米盒子 <a href="http://bbs.xiaomi.cn/thread-8358892-1-1.html" target="_blank">了解更多&raquo;</a>',
	'10月22日星期二中午12点<br/>小米手机3 TD版、小米电视第二轮开放购买<br/>本次开放购买所有产品已售罄，下午3点进行剩余订单专场',
	'小米电视已售罄，您可继续购买小米手机3',
	'全部小米手机3及小米电视已售罄',
	'',
	'成功购买用户请在3小时内下单，下单后3小时内支付<br/>购买成功用户支付通道：<a href="',
	'" target="_blank">支付手机</a><a href="',
	'" target="_blank">支付电视</a><a href="',
	'" target="_blank">支付盒子</a>',
	'成功购买用户请在3小时内下单，下单后3小时内支付',
	'<a href="',
	'" target="_blank">手机及盒子预约查询</a><a href="',
	'" target="_blank">电视预约查询</a>',
	'<a href="',
	'" target="_blank">手机及盒子预约查询</a><a href="',
	'" target="_blank">电视购买查询</a>',
	'<a href="',
	'" target="_blank">手机购买查询</a><a href="',
	'" target="_blank">电视预约查询</a>',
	'<a href="',
	'" target="_blank">手机购买查询</a><a href="',
	'" target="_blank">电视购买查询</a><a href="',
	'" target="_blank">盒子购买查询</a>',
	'&nbsp;',
	'<span class="btn-detail-no">即将开始</span>',
	'<a class="btn-detail" href="#" onClick="showBox(\'phone\');">立即购买</a>',
	'<a class="btn-detail" href="',
	'" target="_blank">立即支付</a>',
	'<span class="btn-detail-no">即将开始</span>',
	'<a class="btn-detail" href="#" onClick="showBox(\'box\');">立即购买</a>',
	'<a class="btn-detail" href="',
	'" target="_blank">立即支付</a>',
	'<span class="btn-detail-no">即将开始</span>',
	'<a class="btn-detail" href="#" onClick="showBox(\'tv\');">立即购买</a>',
	'<a class="btn-detail" href="',
	'" target="_blank">立即支付</a>',
	'<p class="btn-noStart"><span>1999元(16GB)</span>即将开始</p>',
	'<a onClick="showBox(\'phone\');" class="btn-mid"><span>1999元（16GB）</span>立即购买</a>',
	'<a class="btn-mid" href="',
	'" target="_blank"><span>1999元（16GB）</span>立即支付</a>',
	'<p class="btn-noStart"><span>2999元</span>即将开始</p>',
	'<a onClick="showBox(\'box\');" class="btn-mid"><span>2999元</span>立即购买</a>',
	'<a class="btn-mid" href="',
	'" target="_blank"><span>2999元</span>立即支付</a>',
	'<label class="btn-noStart-bottom">即将开始</label>',
	'<a onClick="showBox(\'phone\');" class="btn-bottom">购买手机</a>',
	'<a class="btn-bottom" href="',
	'" target="_blank">支付手机</a>',
	'reback',
	'进入活动',
	'reback_btn_next',
	'重新进入(<span id=\'initCount\'>',
	'</span>)',
	'reback',
	'reback',
	'reback_btn',
	'',
	'userId',
	'XM_',
	'_UN',
	'',
	'',
	'script',
	'https://account.xiaomi.com/pass/userInfoJsonP?userId=',
	'&callback=loginInfo.getAccountInfo',
	'text/javascript',
	'head',
	'LoginArea',
	'LoginArea',
	'欢迎您&nbsp;',
	'！<a href=\'http://order.xiaomi.com/site/logout\'>退出</a>',
	'LoginArea',
	'12px',
	'/',
	'.xiaomi.com',
	'XM_',
	'_UN',
	'userId',
	'phone',
	'phone',
	'box',
	'box',
	'tv',
	'tv',
	'initCount',
	'Util.time()',
	'http://p.www.xiaomi.com/m/zt/open/index.html',
	'undefined',
	'videoBoxMask',
	'px',
	'px',
	'block',
	'<span class="close" onclick="closeBox()" title="关闭">X</span><iframe height="498" width="510" src="{{videoUrl}}" frameborder=0 allowfullscreen ></iframe>',
	'videoBox',
	'data-url',
	'{{videoUrl}}',
	'block',
	'videoBox',
	'none',
	'videoBox',
	'',
	'videoBoxMask',
	'none',
	'_setAccount',
	'UA-24946561-1',
	'_addOrganic',
	'baidu',
	'word',
	'_addOrganic',
	'soso',
	'w',
	'_addOrganic',
	'vnet',
	'kw',
	'_addOrganic',
	'sogou',
	'query',
	'_addOrganic',
	'youdao',
	'q',
	'_addOrganic',
	'so',
	'q',
	'_setDomainName',
	'xiaomi.com',
	'_setAllowLinker',
	'_trackPageview',
	'script',
	'text/javascript',
	'https:',
	'https://ssl',
	'http://www',
	'.google-analytics.com/ga.js',
	'script',
	'setDomainId',
	'trackPageView',
	'script',
	'text/javascript',
	'http://p.www.xiaomi.com/js/xmst.js',
	'script']